//---------------------------------------------------------------------------
//These materials/shaders are part of the NEW InstanceManager implementation
//Written by Matias N. Goldberg ("dark_sylinc")
//---------------------------------------------------------------------------


//---------------------------------------------
//Vertex Shader Input
//---------------------------------------------
struct VS_INPUT
{
	float4 Position	:	POSITION;
	float2 uv0 : TEXCOORD0;

	float4 mat14 : TEXCOORD1;
	float4 mat24 : TEXCOORD2;
	float4 mat34 : TEXCOORD3;

};

struct VS_OUTPUT
{
	float4 Position : POSITION;
	float2 uv0 : TEXCOORD0;
};

//---------------------------------------------
//Main Vertex Shader
//---------------------------------------------
VS_OUTPUT main_vs( in VS_INPUT input,
				   uniform float4x4 worldViewProj)
{
	
	VS_OUTPUT output;
	
	float3x4 worldMatrix;
	worldMatrix[0] = input.mat14;
	worldMatrix[1] = input.mat24;
	worldMatrix[2] = input.mat34;

	float4 worldPos = float4(mul(worldMatrix, input.Position).xyz, 1.0f);

	output.Position = mul(worldViewProj, worldPos);
	output.uv0 = input.uv0;
	
	return output;

}
