#pragma once


// OGRE GROUPS

#define OGRE_MATERIAL_GROUP "og_materials_grp"
#define OGRE_MESH_GROUP "og_meshes_grp"
#define OGRE_TEXTURE_GROUP "og_texture_grp"


// Resource Handler ini stuff


// LOAD PATHS
#define LOAD_PATH_GROUP_NAME_KEY "LOAD_PATH"
#define LOAD_PATH_EXTENSION_KEY "EXTENSIONS"
#define LOAD_PATHS_KEY "PATHS"
#define LOAD_PATH_GROUPS_KEY "GROUPS"

// save / load names

#define CASE_DEFAULT_CASE_PATH "/Data/CASE_CONFIG.yml"
#define CASE_DEFAULT_CASE_NAME "CASE_FILE_NAME"

#define CASE_NAME_KEY "CASE_NAME"
#define CASE_SCENE_KEY "CASE_SCENE"
#define CASE_SCENES_KEY "SCENES"

#define SCENE_NAME_KEY "SCENE_NAME"
#define ATTACHED_SCN_KEY "ATTACTED_SCENES"
#define SCENE_OBJECT_KEY "OBJECTS"
#define SCENE_TYPE_KEY "TYPE"

#define SCENE_POS_KEY "POSITION"
#define SCENE_ROT_KEY "ORIENTATION"
#define SCENE_SCALE_KEY "SCALE"
#define SCENE_ATTACHED_TO "PARENT_NODE"
#define SCENE_ATTACHED_CASE "CASE"
#define SCENE_OBJECTS_KEY "OBJECTS"

#define SCENEOBJ_OBJ_KEY "SCENE_OBJECT_ID"

#define OBJECT_NAME_KEY "OBJECT_NAME"
#define OBJECT_PHYSX_KEY "OBJECT_TYPE"
#define OBJECT_RENDERMESH_KEY "RENDER_MESH"
#define OBJECT_MESHPATH_KEY "MESH_PATH"
#define OBJECT_MATERIAL_KEY "MATERIAL"
#define OBJECT_COLLIDERMESH_KEY "COLLIDER_MESH"
#define OBJECT_MASS_KEY "MASS"

#define SHADER_NAME_KEY "SHADER_NAME"
#define SHADER_FILE_KEY "FILE_NAME"
#define SHADER_TYPE_KEY "SHADER_TYPE"
#define SHADER_VAR_KEY "VARS"
#define SHADER_VALUE_KEY "KEY"

#define MATERIAL_NAME_KEY "MATERIAL_NAME"
#define MATERIAL_FILENAME_KEY "FILE_PATH"
#define MATERIAL_ATTACHED_OBJECT "PARENT_OBJECT"
#define MATERIAL_VERTEX_KEY "VERTEX"
#define MATERIAL_FRAGMENT_KEY "FRAGMENT"
#define MATERIAL_CULLING_KEY "CULLING"
#define MATERIAL_WIREFRAME_KEY "WIREFRAME"
#define MATERIAL_TEXTURE_SIZE_KEY "TEXTURE_SIZE"
#define MATERIAL_TEXTURE_KEY "TEXTURE_IDS"
#define MATERIAL_TEXTURE_NAME_KEY "TEXTURE_NAME"
#define MATERIAL_TEXTURE_POSITION_KEY "TEXTURE_POSITION"
#define MATERIAL_TEXTURE_ADDRESSING_MODE_KEY "TEXTURE_ADDRESSING_MODE"
#define MATERIAL_TEXTURE_SCALE_KEY "TEXTURE_SCALE"

#define MESH_NAME_KEY "MESH_NAME"
#define MESH_MATERIAL_KEY "MATERIAL_ID"

#define MASTER_INSTANCE_SECTION "INSTANCE"
#define MASTER_ID_KEY "ID"

// ini paths
#define DATA_DIRECTORY "/Data"
#define MASTERLIST_LOC DATA_DIRECTORY + "/MasterList.ini"
#define RESOURCELOADER_DATA DATA_DIRECTORY + "/ResourceLoad.yaml"

#define CASE_DIRECTORY DATA_DIRECTORY + "/Case"
#define CASE_INI_LOC CASE_DIRECTORY + "/Cases.ini"

#define SCENE_DIRECTORY DATA_DIRECTORY + "/Scene"
#define SCENE_INI_LOC SCENE_DIRECTORY + "/Scenes.ini"
#define SCENEOBJ_DIRECTORY SCENE_DIRECTORY + "/SceneObj"
#define SCENEOBJ_INI_LOC SCENEOBJ_DIRECTORY + "/ScnObj.ini"

#define MATERIAL_DIRECTORY DATA_DIRECTORY + "/Material"
#define MATERIAL_INI_LOC MATERIAL_DIRECTORY + "/Materials.ini"
#define MATERIALTEXTURE_DIRECTORY MATERIAL_DIRECTORY + "/MaterialTexture"
#define MATERIALTEXTURE_INI_LOC MATERIALTEXTURE_DIRECTORY + "/MaterialTextures.ini"

#define RENDERMESH_DIRECTORY DATA_DIRECTORY + "/RenderMesh"
#define RENDERMESH_INI_LOC RENDERMESH_DIRECTORY + "/RenderMesh.ini"

#define COLLIDERMESH_DIRECTORY DATA_DIRECTORY + "/ColliderMesh"
#define COLLIDERMESH_INI_LOC COLLIDERMESH_DIRECTORY + "/ColliderMesh.ini"

#define SHADER_DIRECTORY DATA_DIRECTORY + "/Shader"
#define SHADER_INI_LOC SHADER_DIRECTORY + "/Shaders.ini"
#define SHADERVAR_DIRECTORY SHADER_DIRECTORY + "/ShaderVar"
#define SHADERVARS_INI_LOC SHADERVAR_DIRECTORY + "/ShaderVars.ini"
#define SHADERVALUES_INI_LOC SHADERVAR_DIRECTORY + "/ShaderValues.ini"

#define IMAGE_DIRECTORY DATA_DIRECTORY + "/Image"
#define IMAGE_INI_LOC IMAGE_DIRECTORY + "/Images.ini"

#define OBJECT_DIRECTORY DATA_DIRECTORY + "/Object"
#define OBJECT_INI_LOC OBJECT_DIRECTORY + "/Objects.ini"


#define RESOURCE_DEFAULT_LOC "resource_handler_def_loc.txt"
#define GENERAL_RESOURCE_LOC "General_Resource_Loc"
#define RENDER_MESH_LOC "Render_Mesh"
#define COLLIDER_MESH_LOC "Collider_Mesh"
#define MESH_MATERIAL_LOC "Mesh_Materials"
#define IMAGES_LOC "Images"

#define DYNAMIC_NODES_LOC "./Scenes/Dynamic/"
#define DYNAMIC_NODES_FILE "dynamicNodes.ini"

#define STATIC_NODES_LOC "./Scenes/Static/"
#define STATIC_NODES_FILE "StaticNodes.ini"

#define MESH_NODES_LOC "./Scenes/Mesh/"
#define MESH_NODES_FILE "MeshNodes.ini"

#define SECTION_SCENE "SCENE"
#define SECTION_OBJECT "OBJECT"
#define SECTION_PARENT_SCN "PARENT_NODE"
#define KEY_PARENT_SCN "NODE"

#define SECTION_MATERIAL "Material"
#define SECTION_VERTEX_SHADER "Vertex Param"
#define SECTION_FRAGMNET_SHADER "Fragment Param"
#define SECTION_TEXTURE "Textures"

#define NODEKEY_NAME "NAME"
#define NODEKEY_RENDERMESH "RENDER_MESH"
#define NODEKEY_COLLIDERMESH "COLLIDER_MESH"
#define NODEKEY_PHYSXTYPE "PHYSXTYPE"
#define NODEKEY_MASS "MASS"
#define NODEKEY_POSITION "POSITION"
#define NODEKEY_ROTATION "ROTATION"
#define NODEKEY_CASTSHADOW "CAST_SHADOW"
#define NODEKEY_RECEIVESHADOW "RECEIVE_SHADOW"
#define NODEKEY_MATERIAL "MATERIAL"






