#pragma once

#define DATA_DIRECTORY "/Data"
#define MASTERLIST_LOC DATA_DIRECTORY + "/MasterList.ini"

#define CASE_DIRECTORY DATA_DIRECTORY + "/Case"
#define CASE_INI_LOC CASE_DIRECTORY + "/Cases.ini"

#define SCENE_DIRECTORY DATA_DIRECTORY + "/Scene"
#define SCENE_INI_LOC SCENE_DIRECTORY + "/Scenes.ini"
#define SCENEOBJ_DIRECTORY SCENE_DIRECTORY + "/SceneObj"
#define SCENEOBJ_INI_LOC SCENEOBJ_DIRECTORY + "/ScnObj.ini"

#define MATERIAL_DIRECTORY DATA_DIRECTORY + "/Material"
#define MATERIAL_INI_LOC MATERIAL_DIRECTORY + "/Materials.ini"
#define MATERIALTEXTURE_DIRECTORY MATERIAL_DIRECTORY + "/MaterialTexture"
#define MATERIALTEXTURE_INI_LOC MATERIALTEXTURE_DIRECTORY + "/MaterialTextures.ini"

#define RENDERMESH_DIRECTORY DATA_DIRECTORY + "/RenderMesh"
#define RENDERMESH_INI_LOC RENDERMESH_DIRECTORY + "/RenderMesh.ini"

#define COLLIDERMESH_DIRECTORY DATA_DIRECTORY + "/ColliderMesh"
#define COLLIDERMESH_INI_LOC COLLIDERMESH_DIRECTORY + "/ColliderMesh.ini"

#define SHADER_DIRECTORY DATA_DIRECTORY + "/Shader"
#define SHADER_INI_LOC SHADER_DIRECTORY + "/Shaders.ini"
#define SHADERVAR_DIRECTORY SHADER_DIRECTORY + "/ShaderVar"
#define SHADERVARS_INI_LOC SHADERVAR_DIRECTORY + "/ShaderVars.ini"
#define SHADERVALUES_INI_LOC SHADERVAR_DIRECTORY + "/ShaderValues.ini"

#define IMAGE_DIRECTORY DATA_DIRECTORY + "/Image"
#define IMAGE_INI_LOC IMAGE_DIRECTORY + "/Images.ini"

#define OBJECT_DIRECTORY DATA_DIRECTORY + "/Object"
#define OBJECT_INI_LOC OBJECT_DIRECTORY + "/Objects.ini"





