#pragma once


#define DATA_DIRECTORY "/Data"
#define MASTERLIST_LOC DATA_DIRECTORY + "/MasterList.ini"
#define RESOURCELOADER_DATA DATA_DIRECTORY + "/ResourceLoad.ini"

#define CASE_DIRECTORY DATA_DIRECTORY + "/Case"
#define CASE_INI_LOC CASE_DIRECTORY + "/Cases.ini"

#define SCENE_DIRECTORY DATA_DIRECTORY + "/Scene"
#define SCENE_INI_LOC SCENE_DIRECTORY + "/Scenes.ini"
#define SCENEOBJ_DIRECTORY SCENE_DIRECTORY + "/SceneObj"
#define SCENEOBJ_INI_LOC SCENEOBJ_DIRECTORY + "/ScnObj.ini"

#define MATERIAL_DIRECTORY DATA_DIRECTORY + "/Material"
#define MATERIAL_INI_LOC MATERIAL_DIRECTORY + "/Materials.ini"
#define MATERIALTEXTURE_DIRECTORY MATERIAL_DIRECTORY + "/MaterialTexture"
#define MATERIALTEXTURE_INI_LOC MATERIALTEXTURE_DIRECTORY + "/MaterialTextures.ini"

#define RENDERMESH_DIRECTORY DATA_DIRECTORY + "/RenderMesh"
#define RENDERMESH_INI_LOC RENDERMESH_DIRECTORY + "/RenderMesh.ini"

#define COLLIDERMESH_DIRECTORY DATA_DIRECTORY + "/ColliderMesh"
#define COLLIDERMESH_INI_LOC COLLIDERMESH_DIRECTORY + "/ColliderMesh.ini"

#define SHADER_DIRECTORY DATA_DIRECTORY + "/Shader"
#define SHADER_INI_LOC SHADER_DIRECTORY + "/Shaders.ini"
#define SHADERVAR_DIRECTORY SHADER_DIRECTORY + "/ShaderVar"
#define SHADERVARS_INI_LOC SHADERVAR_DIRECTORY + "/ShaderVars.ini"
#define SHADERVALUES_INI_LOC SHADERVAR_DIRECTORY + "/ShaderValues.ini"

#define IMAGE_DIRECTORY DATA_DIRECTORY + "/Image"
#define IMAGE_INI_LOC IMAGE_DIRECTORY + "/Images.ini"

#define OBJECT_DIRECTORY DATA_DIRECTORY + "/Object"
#define OBJECT_INI_LOC OBJECT_DIRECTORY + "/Objects.ini"


#define RESOURCE_DEFAULT_LOC "resource_handler_def_loc.txt"
#define GENERAL_RESOURCE_LOC "General_Resource_Loc"
#define RENDER_MESH_LOC "Render_Mesh"
#define COLLIDER_MESH_LOC "Collider_Mesh"
#define MESH_MATERIAL_LOC "Mesh_Materials"
#define IMAGES_LOC "Images"

#define DYNAMIC_NODES_LOC "./Scenes/Dynamic/"
#define DYNAMIC_NODES_FILE "dynamicNodes.ini"

#define STATIC_NODES_LOC "./Scenes/Static/"
#define STATIC_NODES_FILE "StaticNodes.ini"

#define MESH_NODES_LOC "./Scenes/Mesh/"
#define MESH_NODES_FILE "MeshNodes.ini"

#define SECTION_SCENE "SCENE"
#define SECTION_OBJECT "OBJECT"
#define SECTION_PARENT_SCN "PARENT_NODE"
#define KEY_PARENT_SCN "NODE"

#define SECTION_MATERIAL "Material"
#define SECTION_VERTEX_SHADER "Vertex Param"
#define SECTION_FRAGMNET_SHADER "Fragment Param"
#define SECTION_TEXTURE "Textures"

#define NODEKEY_NAME "NAME"
#define NODEKEY_RENDERMESH "RENDER_MESH"
#define NODEKEY_COLLIDERMESH "COLLIDER_MESH"
#define NODEKEY_PHYSXTYPE "PHYSXTYPE"
#define NODEKEY_MASS "MASS"
#define NODEKEY_POSITION "POSITION"
#define NODEKEY_ROTATION "ROTATION"
#define NODEKEY_CASTSHADOW "CAST_SHADOW"
#define NODEKEY_RECEIVESHADOW "RECEIVE_SHADOW"
#define NODEKEY_MATERIAL "MATERIAL"






